global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # FastAPI应用指标
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['app:8000', 'app-replica:8001']
    metrics_path: '/health/metrics'
    scrape_interval: 10s

  # Consul服务发现
  - job_name: 'consul-services'
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['fastapi-service']
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_service_id]
        target_label: instance

  # PostgreSQL指标
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis指标
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx指标
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  # 节点指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Consul指标
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
