apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi-app
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-lb
  namespace: fastapi-app
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
